dist: trusty
sudo: required

addons:
  ssh_known_hosts:
    - github.com
    - git.coding.net
  apt:
    packages:
      - nasm

env:
  global:
    - ATOM_WRITER_PATCH_URL=https://raw.githubusercontent.com/wafer-li/hexo-generator-atom-markdown-writer-meta/9f8ab23d42a60a9fa7ef8eed161f216a7716d14d/lib/generator.js
    - ATOM_WRITER_PATH=node_modules/hexo-generator-atom-markdown-writer-meta/lib/generator.js
    - LOCAL_SEARCH_SCRIPT_URL=https://gist.githubusercontent.com/wafer-li/b41db8f460065ad541de755e7423aa76/raw/aac108319164bccb3621a2699d2d6e2846a59847/localsearch.min.swig
    - THEME_LOCAL_SEARCH_PATH=themes/next-reloaded/layout/_third-party/search/localsearch.swig
    - TZ=Asia/Tokyo

language: node_js
node_js: node

branches:
  only:
    - source

git:
  depth: false
  submodules: false

cache:
  apt: true
  directories:
    - node_modules


before_install:
  # Git Config
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git config --global user.name "wafer-li"
  - git config --global user.email "omyshokami@gmail.com"

  # Restore last modified time
  - "git ls-files -z | while read -d '' path; do touch -d \"$(git log -1 --format=\"@%ct\" \"$path\")\" \"$path\"; done"

  # Submodules
  - git submodule update --recursive --remote --init

  # Deploy history
  - git clone --branch=master --single-branch https://github.com/wafer-li/wafer-li.github.io.git .deploy_git

  # SSH Setup
  - openssl aes-256-cbc -K $encrypted_693585a97b8c_key -iv $encrypted_693585a97b8c_iv -in blog_deploy_key.enc -out blog_deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./blog_deploy_key
  - ssh-add ./blog_deploy_key

install: npm install

before_script:
  # Patch atom writer generator
  - curl $ATOM_WRITER_PATCH_URL >| ${ATOM_WRITER_PATH}

  # Replace the local search script
  - curl ${LOCAL_SEARCH_SCRIPT_URL} >| ${THEME_LOCAL_SEARCH_PATH}

  ## Theme Dependencies
  - cd themes/next-reloaded
  # canvas-nest
  - git clone https://github.com/theme-next/theme-next-canvas-nest source/lib/canvas-nest
  # fancybox3
  - git clone https://github.com/theme-next/theme-next-fancybox3 source/lib/fancybox
  # reading_progress
  - git clone https://github.com/theme-next/theme-next-reading-progress source/lib/reading_progress
  # pangu
  - git clone https://github.com/theme-next/theme-next-pangu.git source/lib/pangu
  # bookmark
  - git clone -b dist https://github.com/theme-next/theme-next-bookmark.git source/lib/bookmark

  - cd ../..

script:
  - hexo clean
  - hexo g -d
