dist: trusty
sudo: required

addons:
  apt:
    packages:
      - nasm

language: node_js
node_js: node

branches:
    only:
        - source

git:
    submodules: false

before_install:
    # Git Config
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git config --global user.name "wafer-li"
    - git config --global user.email "omyshokami@gmail.com"
    - git submodule update --recursive --remote --init

install: npm install

cache:
  directories:
    - "node_modules"

before_script:
    - sed -i "s/git@github.com:/https:\/\/wafer-li:${GH_TOKEN}@github.com\//" source/_data/next.yml
    - sed -i "s/git@git.coding.net:/https:\/\/wafer-li:${CODING_TOKEN}@git.coding.net\//" source/_data/next.yml

    ## Theme Dependencies
    - cd themes/next-reloaded
    # canvas-nest
    - git clone https://github.com/theme-next/theme-next-canvas-nest source/lib/canvas-nest
    # fancybox3
    - git clone https://github.com/theme-next/theme-next-fancybox3 source/lib/fancybox
    # reading_progress
    - git clone https://github.com/theme-next/theme-next-reading-progress source/lib/reading_progress

    - cd ../..

script:
    - hexo clean
    - hexo g -d --config source/_data/next.yml
