dist: trusty
sudo: required

addons:
    ssh_known_hosts:
        - github.com
        - coding.net
    apt:
        packages:
            - nasm

env:
    - ATOM_WRITER_PATCH_URL=https://raw.githubusercontent.com/wafer-li/hexo-generator-atom-markdown-writer-meta/9f8ab23d42a60a9fa7ef8eed161f216a7716d14d/lib/generator.js ATOM_WRITER_DIR=node_modules/hexo-generator-atom-markdown-writer-meta/ TZ=Asia/Tokyo

language: node_js
node_js: node

branches:
    - source

git:
    depth: false
    submodules: false

cache:
    apt: true
    directories:
        - node_modules


before_install:
    # Git Config
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git config --global user.name "wafer-li"
    - git config --global user.email "omyshokami@gmail.com"

    # Restore last modified time
    - chmod +x git_reset_mtime.py
    - python3 ./git_reset_mtime.py

    # Submodules
    - git submodule update --recursive --remote --init

    # Deploy history
    - git clone --branch=master --single-branch https://github.com/wafer-li/wafer-li.github.io.git .deploy_git

install: npm install

before_script:
    #- sed -i "s/git@github.com:/https:\/\/wafer-li:${GH_TOKEN}@github.com\//" source/_data/next.yml
    #- sed -i "s/git@git.coding.net:/https:\/\/wafer-li:${CODING_TOKEN}@git.coding.net\//" source/_data/next.yml

    # Patch atom writer generator
    - curl $ATOM_WRITER_PATCH_URL >| ${ATOM_WRITER_DIR}/lib/generator.js

    ## Theme Dependencies
    - cd themes/next-reloaded
    # canvas-nest
    - git clone https://github.com/theme-next/theme-next-canvas-nest source/lib/canvas-nest
    # fancybox3
    - git clone https://github.com/theme-next/theme-next-fancybox3 source/lib/fancybox
    # reading_progress
    - git clone https://github.com/theme-next/theme-next-reading-progress source/lib/reading_progress

    - cd ../..

script:
    - hexo clean
    - hexo g --config source/_data/next.yml

before_deploy:
    - openssl aes-256-cbc -K $encrypted_693585a97b8c_key -iv $encrypted_693585a97b8c_iv -in blog_deploy_key.enc -out blog_deploy_key -d
    - eval "$(ssh-agent -s)"
    - chmod 600 ./blog_deploy_key
    - ssh-add ./blog_deploy_key

deploy:
    - hexo d --config source/_data/next.yml
